# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-crlf

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        exclude: ^CHANGELOG\.md$
