name: Test Build

on:
  push:
jobs:
  build:
    name: "Test Build"

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            yarn-task: build:linux
          - os: ubuntu-latest
            name: snap
            yarn-task: build:snap
          - os: macos-latest
            name: mac
            yarn-task: build:mac
          - os: windows-latest
            name: win
            yarn-task: build:win

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Install NPM Packages
        run: |
          yarn install --immutable --network-timeout 120000
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn ${{ matrix.yarn-task }}
      # Possibly set up some basic unit testing just to make sure parts render and none of the libraries are straight up breaking
      - uses: actions/upload-artifact@v2
        with:
          name: built-app-${{ matrix.name }}
          path: |
            app/main/dist/*.*
