name: Test Build

on:
  push:
jobs:
  prepare:
    name: "Prepare"
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-build-${{ hashFiles('yarn.lock') }}
      - name: Install NPM Packages
        run: |
          yarn install --immutable --network-timeout 120000
      - name: Build
        run:  |
          yarn build
          tree
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: prepare
          path: app/main/build/
  build:
    needs: prepare
    name: "Test Build"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            yarn-task: build:linux
          - os: ubuntu-latest
            name: snap
            yarn-task: build:snap
          - os: macos-latest
            name: mac
            yarn-task: build:mac
          - os: windows-latest
            name: win
            yarn-task: build:win
          - os: windows-latest
            name: win-a64
            yarn-task: build:win-a64
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-build-${{ hashFiles('yarn.lock') }}
      - name: Install NPM Packages
        run: |
          yarn install --immutable --network-timeout 120000
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: prepare
          path: app/main/build
      - name: Build
        run: lerna run ${{ matrix.yarn-task }} --stream
      # Possibly set up some basic unit testing just to make sure parts render and none of the libraries are straight up breaking
      - uses: actions/upload-artifact@v3
        with:
          name: built-app-${{ matrix.name }}
          path: |
            app/main/dist/*.*
