name: Release-please
on:
  push:
    branches:
      - master
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
      sha: ${{ steps.release.outputs.sha }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    # https://github.com/google-github-actions/release-please-action in case more config is needed
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          # In case we need to add a PAT and have the pr's trigger actions
          # token: ${{ secrets.PAT }}
          # See how to configure file https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
          # See output info at https://github.com/google-github-actions/release-please-action#configuration for variables
          # Trigger more steps using "if: ${{ steps.release.outputs.release_created }}"
  build:
    name: Build
    if: needs.release-please.outputs.release_created
    needs: release-please
    uses: ./.github/workflows/build.yml
  publish:
    name: Publish
    if: needs.release-please.outputs.release_created
    needs: ['release-please', 'build']
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Upload Release Assets
        id: upload-release-asset
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: needs.release-please.outputs.tag
          files: |
            **/latest*
            **/*.deb
            **/*.rpm
            **/*.dmg
            **/*.AppImage
            **/*.zip
            **/*.exe
            **/*.blockmap
