on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      sha: ${{ steps.release.outputs.sha }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    # https://github.com/google-github-actions/release-please-action in case more config is needed
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          # In case we need to add a PAT and have the pr's trigger actions
          #token: ${{ secrets.PAT }}
          # See how to configure file https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
          # See output info at https://github.com/google-github-actions/release-please-action#configuration for variables
          # Trigger more steps using "if: ${{ steps.release.outputs.release_created }}"
  build:
    name: Build
    needs: release-please
    uses: ./.github/workflows/build.yml
  publish:
    name: Pubish
    needs: ['release-please', 'build']
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Upload Release Asset(s)
        id: upload-release-asset
        uses: sekwah41/upload-release-assets@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release-please.outputs.upload_url }}
          asset_path: |
            app/main/dist/latest*
            app/main/dist/*.deb
            app/main/dist/*.rpm
            app/main/dist/*.dmg
            app/main/dist/*.AppImage
            app/main/dist/*.zip
            app/main/dist/*.exe
            app/main/dist/*.blockmap
