name: Release
on:
  push:
    branches:
      - master
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
    outputs:
      tag: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
      sha: ${{ steps.release.outputs.sha }}
      upload_url: ${{ steps.release.outputs.upload_url }}
  build:
    name: "Build"
    needs: release-please
    if: needs.release-please.outputs.release_created
    uses: ./.github/workflows/build.yml
  publish:
    name: Publish
    needs:
      - build
      - release-please
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Upload Release Assets
        id: upload-release-asset
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.release-please.outputs.tag }}
          files: |
            **/latest*
            **/*.deb
            **/*.rpm
            **/*.dmg
            **/*.AppImage
            **/*.zip
            **/*.exe
            **/*.snap
            **/*.blockmap
