on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      sha: ${{ steps.release.outputs.sha }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    # https://github.com/google-github-actions/release-please-action in case more config is needed
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          # In case we need to add a PAT and have the pr's trigger actions
          #token: ${{ secrets.PAT }}
          # See how to configure file https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md
          # See output info at https://github.com/google-github-actions/release-please-action#configuration for variables
          # Trigger more steps using "if: ${{ steps.release.outputs.release_created }}"

  build:
    needs: release-please
    name: "Build"

    runs-on: ${{ matrix.os }}

    if: ${{ needs.release-please.outputs.release_created }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            yarn-task: build:linux
          - os: macos-latest
            name: mac
            yarn-task: build:mac
          - os: windows-latest
            name: win
            yarn-task: build:win

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Install NPM Packages
        run: |
          yarn install --immutable --network-timeout 120000
      - name: Build
        run: yarn ${{ matrix.yarn-task }}
      # Possibly set up some basic unit testing just to make sure parts render and none of the libraries are straight up breaking
      - uses: actions/upload-artifact@v2
        with:
          name: built-app-${{ matrix.name }}
          path: |
            app/main/dist/*.*
      - name: Upload Release Asset(s)
        id: upload-release-asset
        uses: sekwah41/upload-release-assets@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release-please.outputs.upload_url }}
          asset_path: |
            app/main/dist/latest*
            app/main/dist/*.deb
            app/main/dist/*.rpm
            app/main/dist/*.dmg
            app/main/dist/*.AppImage
            app/main/dist/*.zip
            app/main/dist/*.exe
            app/main/dist/*.blockmap
